== Mac App

. Create a new Workspace in Xcode (File -> New -> Workspace)

. Save as Notes.xcworkspace

. File -> New  -> Project, OS X -> Application, Cocoa Application
+
Product name: Notes, Language: Swift, Org. name and identifier: whatever you like, Create Document-Based Application = on, Use Core Data = off, include unit and UI tests = both on
+
When saving it, change 'Add to' to the 'Notes' workspace that you just created

[NOTE]
====
UI tests will only work on OS X 10.11 'El Capitan'.
====

. Run the app and you can already create new 'documents' by pressing Cmd-N.

=== The document model

. Open Document.swift
. Add an NSAttributedString property called +text+ - set its default value to the empty attributed string

. Implement +dataOfType+ to convert the string to an NSData containing RTFD and return it (or throw an error)
. Implement +readFromData+ to convert the NSData into an NSAttributedString or throw an error

. Run the app, you can now save and open files - the UI doesn't change yet, we'll do that next

==== A basic UI

. Open Document.xib

. Delete the label

. Add a text view, resize it to fill the window (leaving some margins)
. Select it
. Editor->Resolve Auto Layout Issues->Reset to Suggested Constraints
	. Text view will now resize to fit the window
. Select the Text View (it's a child of the Bordered Scroll View's Clip View)
. Open Bindings inspector
	. Bind Attributed String to File's Owner; model key path = self.text
	
. Run the app; you can now enter and save text, close the document, re-open it; you get free undo and revision control; LOTS of stuff is taken care of for you!

==== Architecting for attachments

. Right now the document class has a single property: 'text'
. It's also stored as a single file
. We want to include attachments, and the easiest way to do that is to create a 'file package' - this means we won't have to read the entire thing into memory, which might be a problem if those attachments are large
. This means we need to use NSFileWrapper

	. An NSFileWrapper is an object that represents either a single file, or a directory of multiple files (each of which can itself be a file wrapper representing a directory)
	. In this app we'll use directory file wrappers; they'll contain at least two files:
		 . A file that contains general info about the document, named "Document.plist"
		 . The .rtfd file containing the text, called "Text.rtfd"
		 . Plus any attached files, which will be kept in a directory called Attachments (so that you can drop files with any name in, including ones named "Document.plist" and "Text.rtf")

. This means we need to implement methods that load from and save to a file wrapper

. Go to project -> Info, scroll down to Document Types, turn on Document is distributed as a bundle

. Implement +readFromFileWrapper+ and +fileWrapperOfType+ (plus related funcs and enums)

. Re-run the app, make a document, save it
. Locate that document in the Finder and right click, choose Show Package Contents - behold, Text.rtf!

==== Adding attachments

. Now we'll add support for actually storing attachments



==== Adding support for QuickLook